reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Example/Pods

#### Rules
line_length: 500 # Monitors are big these days