# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run the iOS lane"

  lane :test do
    swiftlint(
      mode: :lint,                            # SwiftLint mode: :lint (default) or :autocorrect
      executable: ENV["SWIFT_LINT_PATH"], # The SwiftLint binary path (optional). Important if you've installed it via CocoaPods
      reporter: "junit",                       # The custom reporter to use (optional)
      config_file: ".swiftlint.yml",       # The path of the configuration file (optional)
      ignore_exit_status: false                # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )

    run_tests(
      workspace: ENV["WORKSPACE"],
      devices: ["iPhone 7"],
      scheme: ENV["SCHEME"]
    )
  end
end
